### ISSUE TITLE
not attaching

### ISSUE THREAD

**Issue by dzogrim** [johnko/ssh-multi#1]
Hi!
Is there any issue with tmux 2.1 and ssh-multi?
I could not use the script again… I always have new window not attaching in panes and it is not keeping the pane from where I launch the script opened… I guess it's since the 2.1 version. Right?
I've been looking https://raw.githubusercontent.com/tmux/tmux/master/CHANGES but I didn't see what I could change to make it work again from changes :/
Example with 4 servers: only 3 are showing, beside pane with "ssh-muti" command (so 4 panes in 0), and a new window (1) with a 4th one (not synced).
window1 : http://hpics.li/147da19
window2 : http://hpics.li/c3a6a10

**Comment by johnko** [comment]
From your screenshots, I think you are trying to run ssh-multi (which uses tmux) while you already are using tmux.

For some reason Line 29 doesn't detect your existing session/window while you are in tmux and launches a new one.

I think a workaround is to try your ssh-multi command from a new Terminal.app window that's not in tmux OR on Line 14, to set:

```
NEWSESSION=0
```

**Comment by dzogrim** [comment]
Thanks @johnko ; I tyried to change NEWSESSION value… without any effect ; anyway it's actually working if I don't first launch tmux as you said… Now the really strange thing is I was used to launch it from tmux directly and I can't do it anymore with this tmux version (on two different systems). It's fine, I will change the way I use it… Thanks again.
